#This workflow will build and deploy Lambda
name: Building and Deploying Lambda function

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: buildlambda
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Creating zip of lambda index file
        run: zip -r serverless.zip . -x ".git/*" ".github/*"

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Lambda Update
        run: |
          aws lambda update-function-code --function-name emailVerify --zip-file fileb://${{ github.workspace }}/serverless.zip